const laws=[
 {number:"Cabinet Resolution No. 109 of 2023",title:"Regulating the Real Beneficiary Procedures",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Requires covered legal persons to identify their ultimate natural-person owners or controllers, maintain current registers and provide information to the relevant registrar.",relevance:"The core UAE beneficial-ownership instrument. It uses a 25% ownership or voting-rights test, then control by other means, followed by the senior managing official where no natural person is identified.",topics:"beneficial owner ubo ultimate ownership corporate transparency aml",source:"https://uaelegislation.gov.ae/en/legislations/2176",note:"Replaced Cabinet Decision No. 58 of 2020."},
 {number:"Cabinet Resolution No. 132 of 2023",title:"Administrative Penalties for Real Beneficiary Procedures",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Sets administrative sanctions for breaches of beneficial-ownership procedures, including escalating fines and potential licence suspension for repeated violations.",relevance:"Explains the enforcement consequences of failing to maintain or submit accurate beneficial-owner information.",topics:"beneficial owner ubo penalties ownership",source:"https://uaelegislation.gov.ae/en/legislations/2314",note:"Abrogated Cabinet Decision No. 53 of 2021."},
 {number:"Federal Decree-Law No. 10 of 2025",title:"Anti-Money Laundering and Combating Terrorism and Proliferation Financing",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"The current federal framework for anti-money laundering, counter-terrorist financing and proliferation financing.",relevance:"Provides the current parent AML framework and authorises Cabinet procedures for identifying beneficial owners.",topics:"beneficial owner ubo aml anti-money laundering ctf sanctions",source:"https://uaelegislation.gov.ae/en/legislations/3314",note:"Repealed Federal Decree-Law No. 20 of 2018."},
 {number:"Cabinet Resolution No. 134 of 2025",title:"Executive Regulations of Federal Decree-Law No. 10 of 2025",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Implements the current AML law, including customer due diligence, verification, record keeping and risk-based controls.",relevance:"Relevant when beneficial-owner information must be identified and verified during customer due diligence.",topics:"beneficial owner ubo aml customer due diligence cdd kyc",source:"https://uaelegislation.gov.ae/en/legislations/3857"},
 {number:"Federal Decree-Law No. 45 of 2021",title:"Personal Data Protection Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Creates the federal framework for processing personal data, data-subject rights, security, cross-border transfers and controller and processor obligations.",relevance:"The main federal instrument for organisations evaluating personal-data processing outside the financial free zones.",topics:"data protection privacy personal data cross-border transfer",source:"https://uaelegislation.gov.ae/en/legislations/1972"},
 {number:"Federal Decree-Law No. 47 of 2022",title:"Corporate Tax Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Establishes UAE corporate tax, including taxable persons, exemptions, calculation rules, free-zone provisions and transfer pricing.",relevance:"The primary federal law for corporate-tax questions, read with current decisions and FTA guidance.",topics:"corporate tax free zone transfer pricing taxation",source:"https://uaelegislation.gov.ae/en/legislations/2209"},
 {number:"Cabinet Resolution No. 49 of 2023",title:"Natural Persons Subject to Corporate Tax",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Specifies when business or business activities conducted by resident or non-resident natural persons fall within the corporate-tax regime.",relevance:"Useful for questions on whether an individual carrying on business in the UAE is within corporate-tax scope.",topics:"corporate tax natural person individual business taxation",source:"https://uaelegislation.gov.ae/en/legislations/2219"},
 {number:"Federal Decree-Law No. 33 of 2021",title:"Regulation of Employment Relationships",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates private-sector employment relationships, including contracts, working time, leave, termination and end-of-service benefits.",relevance:"The central federal instrument for private-sector labour and termination research, subject to its scope and later amendments.",topics:"labour employment termination end of service leave probation notice",source:"https://uaelegislation.gov.ae/en/legislations/1541"},
 {number:"Federal Decree-Law No. 9 of 2022",title:"Domestic Workers",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates domestic-work relationships, recruitment, employer and worker obligations, working conditions and termination.",relevance:"Domestic workers are governed by a separate statutory regime from the general private-sector employment law.",topics:"domestic workers maid nanny driver employment labour recruitment termination",source:"https://uaelegislation.gov.ae/en/legislations/1593"},
 {number:"Cabinet Resolution No. 106 of 2022",title:"Executive Regulations of the Domestic Workers Law",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Provides detailed implementing rules for Federal Decree-Law No. 9 of 2022 concerning domestic workers.",relevance:"Important for practical questions involving recruitment agencies, contracts, workplace obligations and domestic-worker procedures.",topics:"domestic workers employment recruitment agency maid nanny driver",source:"https://uaelegislation.gov.ae/en/legislations/1620"},
 {number:"Federal Decree-Law No. 32 of 2021",title:"Commercial Companies Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates the formation, governance, management, restructuring and dissolution of commercial companies in the UAE, subject to applicable exclusions and amendments.",relevance:"The core federal company-law source for LLCs, public and private joint-stock companies, governance and corporate administration.",topics:"companies company llc shareholder director governance incorporation liquidation commercial companies",source:"https://uaelegislation.gov.ae/en/legislations/1542"},
 {number:"Federal Decree-Law No. 50 of 2022",title:"Commercial Transactions Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates merchants and commercial activities, commercial obligations and contracts, banking transactions and commercial papers, including cheques.",relevance:"A central source for business-contract, merchant, banking, cheque, brokerage, carriage and commercial-obligation questions.",topics:"commercial transactions merchant contract business cheque banking brokerage carriage trade",source:"https://uaelegislation.gov.ae/en/legislations/1610"},
 {number:"Federal Decree-Law No. 42 of 2022",title:"Civil Procedure Code",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Governs civil procedures before UAE courts within its scope, including jurisdiction, filing, service, hearings, judgments, appeals and enforcement.",relevance:"The primary procedural source for civil and commercial litigation in the onshore UAE court system.",topics:"civil procedure litigation court jurisdiction service appeal enforcement judgment execution lawsuit",source:"https://uaelegislation.gov.ae/en/legislations/1602"},
 {number:"Federal Decree-Law No. 35 of 2022",title:"Law of Evidence in Civil and Commercial Transactions",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates documentary, electronic, testimonial, expert and other evidence in civil and commercial disputes.",relevance:"Critical for questions about burden of proof, electronic evidence, written proof, witness evidence and court-appointed experts.",topics:"evidence burden proof electronic evidence witness expert civil commercial litigation",source:"https://uaelegislation.gov.ae/en/legislations/1612"},
 {number:"Federal Law No. 6 of 2018",title:"Arbitration Law",jurisdiction:"Federal",authority:"UAE Federal Government",status:"In force",summary:"Governs arbitration agreements, tribunals, proceedings, arbitral awards, challenges and enforcement within its scope.",relevance:"The principal federal arbitration statute for UAE-seated arbitrations outside financial-free-zone regimes where applicable.",topics:"arbitration arbitral tribunal award enforcement arbitration agreement dispute resolution",source:"https://uaelegislation.gov.ae/en/legislations/1069"},
 {number:"Federal Decree-Law No. 51 of 2023",title:"Financial Restructuring and Bankruptcy Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Provides the current federal framework for preventive settlement, restructuring, bankruptcy and related court procedures.",relevance:"The principal source for business distress, creditor claims, restructuring and bankruptcy proceedings within its scope.",topics:"bankruptcy insolvency restructuring debtor creditor liquidation financial distress",source:"https://uaelegislation.gov.ae/en/legislations/2190"},
 {number:"Federal Decree-Law No. 46 of 2021",title:"Electronic Transactions and Trust Services",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates electronic transactions, electronic signatures, electronic seals and trust services and supports legal recognition of qualifying electronic records.",relevance:"Important for digital contracting, e-signatures, electronic records and trust-service questions.",topics:"electronic transactions e-signature digital signature electronic record trust services contract",source:"https://uaelegislation.gov.ae/en/legislations/1539"},
 {number:"Federal Decree-Law No. 34 of 2021",title:"Countering Rumours and Cybercrimes",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Creates offences and penalties relating to unlawful access, misuse of information technology, online content and other cyber-enabled conduct.",relevance:"The principal federal cybercrime source for online misconduct, unauthorised access and technology-related offences.",topics:"cybercrime cyber crime hacking online social media privacy technology offence rumours",source:"https://uaelegislation.gov.ae/en/legislations/1526"},
 {number:"Federal Law by Decree No. 31 of 2021",title:"Crimes and Penalties Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Sets the general federal framework for criminal liability, offences, penalties and related substantive criminal-law principles.",relevance:"The core substantive criminal-law source, read together with special criminal legislation and the Criminal Procedures Law.",topics:"criminal crime penal penalties offence fraud theft assault criminal law",source:"https://uaelegislation.gov.ae/en/legislations/1529"},
 {number:"Federal Decree-Law No. 38 of 2022",title:"Criminal Procedures Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates criminal investigation, prosecution, trial, appeals and enforcement of criminal judgments.",relevance:"The principal procedural framework for criminal cases in the federal legal system and relevant local courts applying federal criminal procedure.",topics:"criminal procedure police prosecution investigation trial appeal bail criminal court",source:"https://uaelegislation.gov.ae/en/legislations/1604"},
 {number:"Federal Decree-Law No. 36 of 2021",title:"Trademarks Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates trademark registration, protection, transfer, licensing, enforcement, geographical indications and infringement-related remedies and penalties.",relevance:"The main federal source for brand-name, logo, trademark registration and infringement research.",topics:"trademark brand logo intellectual property ip infringement registration geographical indication",source:"https://uaelegislation.gov.ae/en/legislations/1535"},
 {number:"Cabinet Resolution No. 57 of 2022",title:"Executive Regulations of the Trademarks Law",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Sets procedures and requirements for trademark applications, registration, publication, objections and related administration.",relevance:"Useful for practical trademark-filing and registration-process questions that the main statute leaves to implementing rules.",topics:"trademark registration application opposition intellectual property brand",source:"https://uaelegislation.gov.ae/en/legislations/1562"},
 {number:"Federal Law No. 11 of 2021",title:"Regulation and Protection of Industrial Property Rights",jurisdiction:"Federal",authority:"UAE Federal Government",status:"In force",summary:"Protects patents, utility models, industrial designs, integrated circuits and undisclosed information and regulates registration and exploitation of those rights.",relevance:"The primary federal source for patents and other industrial-property rights in the UAE, including free zones.",topics:"patent industrial property invention design utility model intellectual property ip trade secret",source:"https://uaelegislation.gov.ae/en/legislations/1506"},
 {number:"Federal Decree-Law No. 41 of 2024",title:"Personal Status Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Provides the current federal framework for personal-status matters within its scope, including marriage, divorce, custody, guardianship and succession-related matters.",relevance:"The principal current federal personal-status reference, subject to applicable rules for non-Muslims and financial free zones.",topics:"personal status family marriage divorce custody guardianship inheritance family law",source:"https://uaelegislation.gov.ae/en/legislations/2770"},
 {number:"Federal Decree-Law No. 41 of 2022",title:"Civil Personal Status",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Establishes a civil personal-status regime for non-Muslims within the scope defined by the legislation.",relevance:"Relevant to civil marriage, divorce, custody and inheritance questions for persons falling within its application.",topics:"civil personal status non muslim marriage divorce custody inheritance family",source:"https://uaelegislation.gov.ae/en/legislations/1730"},
 {number:"Federal Decree-Law No. 14 of 2025",title:"Central Bank, Financial Institutions and Insurance Framework",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Provides the current statutory framework for the Central Bank, regulation of licensed financial institutions and activities, and insurance business.",relevance:"A foundational source for banking, finance, payments, licensing, supervision and insurance regulation in the UAE.",topics:"central bank cbuae banking bank finance insurance financial institution payments licensing",source:"https://uaelegislation.gov.ae/en/legislations/3284"},
 {number:"DIFC Law No. 5 of 2020",title:"DIFC Data Protection Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"The DIFC’s independent data-protection framework governing personal-data processing, rights, accountability and international transfers.",relevance:"Applies separately from the federal data-protection regime where the DIFC framework governs.",topics:"data protection privacy personal data difc",source:"https://www.difc.com/business/laws-and-regulations/legal-database"},
 {number:"DIFC Law No. 2 of 2019",title:"DIFC Employment Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"Regulates employment relationships in the DIFC, including employment terms, leave, termination and workplace rights and obligations.",relevance:"DIFC employment is governed by its own legal regime rather than the federal private-sector labour law for matters within DIFC jurisdiction.",topics:"difc employment labour termination leave employee employer dews",source:"https://www.difc.com/business/laws-and-regulations/legal-database"},
 {number:"DIFC Law No. 5 of 2018",title:"DIFC Companies Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"Provides the principal company-law framework for entities incorporated in the DIFC.",relevance:"Relevant to DIFC incorporation, directors, shareholders, corporate governance and company administration.",topics:"difc company companies incorporation shareholder director governance",source:"https://www.difc.com/business/laws-and-regulations/legal-database"},
 {number:"DIFC Law No. 6 of 2004",title:"DIFC Contract Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"Sets the DIFC framework for contract formation, interpretation, performance, non-performance and remedies.",relevance:"A core source for commercial-contract disputes governed by DIFC law.",topics:"difc contract agreement breach damages performance commercial",source:"https://www.difc.com/business/laws-and-regulations/legal-database"},
 {number:"DIFC Law No. 1 of 2019",title:"DIFC Insolvency Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"Regulates insolvency, restructuring, administration, liquidation and creditor-related procedures for entities within its scope.",relevance:"The main DIFC insolvency framework and distinct from the federal bankruptcy regime.",topics:"difc insolvency bankruptcy restructuring liquidation creditor debtor",source:"https://www.difc.com/business/laws-and-regulations/legal-database"},
 {number:"DIFC Law No. 1 of 2008",title:"DIFC Arbitration Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"Provides the arbitration framework applicable in the DIFC, including recognition and enforcement of arbitral awards.",relevance:"Important for DIFC-seated arbitration and enforcement questions and distinct from the federal arbitration statute.",topics:"difc arbitration arbitral award enforcement dispute resolution",source:"https://www.difc.com/business/laws-and-regulations/legal-database"},
 {number:"DFSA AML Module — VER30/04-26",title:"Anti-Money Laundering, Counter-Terrorist Financing and Sanctions Module",jurisdiction:"DIFC",authority:"Dubai Financial Services Authority (DFSA)",status:"In force",summary:"Sets the DFSA’s risk-based AML, customer risk assessment, customer due diligence, sanctions, MLRO, suspicious activity reporting, training and record-keeping requirements for Relevant Persons.",relevance:"The primary DFSA Rulebook module for AML, CTF, proliferation-financing and sanctions compliance by regulated firms, market institutions, DNFBPs and registered auditors in the DIFC.",topics:"dfsa difc aml anti-money laundering ctf sanctions customer due diligence cdd kyc mlro suspicious activity sar",source:"https://dfsaen.thomsonreuters.com/rulebook/anti-money-laundering-counter-terrorist-financing-and-sanctions-module-aml-ver3004-26",note:"Use the Rulebook’s current-version link when a later consolidated version is published."},
 {number:"DFSA COB Module — VER51/07-26",title:"Conduct of Business Module",jurisdiction:"DIFC",authority:"Dubai Financial Services Authority (DFSA)",status:"In force",summary:"Governs client classification, communications and marketing, client agreements, suitability, conflicts, record keeping and activity-specific conduct requirements for DFSA Authorised Firms.",relevance:"The central DFSA conduct source for firms carrying on financial services in or from the DIFC.",topics:"dfsa difc conduct of business cob client classification suitability marketing conflicts custody money services crypto",source:"https://dfsaen.thomsonreuters.com/rulebook/conduct-business-module-cob-ver5107-26"},
 {number:"ADGM Companies Regulations",title:"Companies Regulations",jurisdiction:"ADGM",authority:"Abu Dhabi Global Market",status:"In force",summary:"Provides the company-law framework for entities incorporated and registered in ADGM.",relevance:"Relevant to ADGM company formation, directors, shareholders, filings, governance and corporate administration.",topics:"adgm company companies incorporation shareholder director governance registration",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"ADGM Employment Regulations",title:"Employment Regulations",jurisdiction:"ADGM",authority:"Abu Dhabi Global Market",status:"In force",summary:"Regulates employment relationships within ADGM under its independent legal framework.",relevance:"ADGM employment questions should be checked against this regime rather than automatically applying federal private-sector labour law.",topics:"adgm employment labour employee employer termination leave",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"ADGM Insolvency Regulations",title:"Insolvency Regulations",jurisdiction:"ADGM",authority:"Abu Dhabi Global Market",status:"In force",summary:"Provides ADGM rules for insolvency, administration, restructuring and liquidation within its jurisdiction.",relevance:"The principal ADGM insolvency framework, distinct from the federal bankruptcy regime.",topics:"adgm insolvency bankruptcy restructuring liquidation creditor debtor",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"ADGM Arbitration Regulations",title:"Arbitration Regulations",jurisdiction:"ADGM",authority:"Abu Dhabi Global Market",status:"In force",summary:"Governs arbitration seated in ADGM and related court support and award-enforcement issues within its scope.",relevance:"A key source for ADGM arbitration and enforcement research.",topics:"adgm arbitration arbitral award enforcement dispute resolution",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"ADGM Data Protection Regulations",title:"Data Protection Regulations",jurisdiction:"ADGM",authority:"Abu Dhabi Global Market",status:"In force",summary:"Sets ADGM’s independent data-protection framework for personal-data processing, rights, governance and transfers.",relevance:"Applies within ADGM where its data-protection regime governs, separately from the UAE federal PDPL.",topics:"adgm data protection privacy personal data transfer controller processor",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"ADGM Financial Services and Markets Regulations",title:"Financial Services and Markets Regulations",jurisdiction:"ADGM",authority:"ADGM Financial Services Regulatory Authority (FSRA)",status:"In force",summary:"Establishes the main legislative framework for regulation of financial services in ADGM and the powers and functions of the FSRA.",relevance:"The foundational statute for authorisation, markets, regulated activities, enforcement and financial-services supervision in ADGM.",topics:"adgm fsra financial services markets regulation authorisation investment banking virtual assets",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"FSRA AML Rules and Guidance",title:"Anti-Money Laundering and Sanctions Rules and Guidance",jurisdiction:"ADGM",authority:"ADGM Financial Services Regulatory Authority (FSRA)",status:"In force",summary:"Establishes the FSRA framework for AML, counter-terrorist and proliferation financing, sanctions compliance, risk assessment, due diligence, suspicious activity reporting and governance.",relevance:"Applies within its scope to ADGM Authorised Persons, Recognised Bodies, DNFBPs and other Relevant Persons.",topics:"fsra adgm aml anti-money laundering sanctions ctf proliferation financing cdd kyc mlro suspicious activity",source:"https://www.adgm.com/media/announcements/adgm-fsra-finalises-enhancements-to-its-anti-money-laundering-framework"},
 {number:"FSRA Conduct of Business Rulebook (COBS)",title:"Conduct of Business Rulebook",jurisdiction:"ADGM",authority:"ADGM Financial Services Regulatory Authority (FSRA)",status:"In force",summary:"Sets conduct standards for ADGM Authorised Persons, including client classification, suitability, client assets, conflicts and disclosures.",relevance:"The principal FSRA conduct source for regulated financial services in ADGM.",topics:"fsra adgm conduct of business cobs client classification suitability client money custody virtual assets",source:"https://www.adgm.com/legal-framework/rules-and-regulations"},
 {number:"ADGM Beneficial Ownership and Control Regulations 2022",title:"Beneficial Ownership and Control Regulations",jurisdiction:"ADGM",authority:"ADGM Registration Authority",status:"In force",summary:"Requires applicable ADGM entities to ascertain their true beneficial owners, maintain an up-to-date beneficial-owner record and notify the Registrar of relevant changes.",relevance:"Uses ownership, control and management tests and forms the entity-level beneficial-ownership framework in ADGM.",topics:"beneficial owner ultimate beneficial owner ubo adgm registration authority ownership control register filing",source:"https://www.adgm.com/operating-in-adgm/obligations-of-adgm-registered-entities/beneficial-ownership-and-control"}
];
const form=document.querySelector("#search-form"),query=document.querySelector("#query"),results=document.querySelector("#results"),intro=document.querySelector("#intro"),list=document.querySelector("#result-list"),title=document.querySelector("#results-title"),count=document.querySelector("#results-count"),filter=document.querySelector("#jurisdiction"),copy=document.querySelector("#copy");let current=[];
const synonymGroups=[
 ["ubo","beneficial owner","beneficial ownership","ultimate beneficial owner","ownership control"],
 ["aml","anti money laundering","money laundering","financial crime"],
 ["ctf","counter terrorist financing","terrorist financing"],
 ["kyc","know your customer","customer due diligence","cdd"],
 ["privacy","data protection","personal data"],
 ["labour","labor","employment","employee"],
 ["termination","dismissal","end of service"],
 ["corporate tax","business tax","taxation"],
 ["central bank","cbuae","banking regulator"],
 ["dfsa","dubai financial services authority","difc regulator"],
 ["fsra","financial services regulatory authority","adgm regulator"],
 ["cma","sca","capital market authority","securities and commodities authority","capital markets regulator"],
 ["conduct","conduct of business","cob","cobs"],
 ["sanction","sanctions","targeted financial sanctions","tfs"],
 ["virtual asset","virtual assets","crypto","digital asset","token"]
];
function normalise(value){return value.toLowerCase().replace(/[^\p{L}\p{N}%]+/gu," ").trim()}
function expandTerms(value){const clean=normalise(value),stopwords=new Set(["a","an","and","are","for","from","in","is","of","on","or","the","to","with"]),expanded=new Set([clean,...clean.split(" ").filter(Boolean)]);synonymGroups.forEach(group=>{if(group.some(term=>clean.includes(normalise(term))))group.forEach(term=>{expanded.add(normalise(term));normalise(term).split(" ").forEach(word=>expanded.add(word))})});return [...expanded].filter(term=>term.length>1&&!stopwords.has(term))}
function scoreLaw(law,rawQuery){const phrase=normalise(rawQuery),terms=expandTerms(rawQuery),topics=normalise(law.topics),heading=normalise(`${law.number} ${law.title}`),regulator=normalise(`${law.authority} ${law.jurisdiction}`),body=normalise(`${law.summary} ${law.relevance} ${law.note||""}`);let score=0;if(topics.includes(phrase))score+=20;if(heading.includes(phrase))score+=16;if(regulator.includes(phrase))score+=12;if(body.includes(phrase))score+=8;terms.forEach(term=>{if(topics.includes(term))score+=5;if(heading.includes(term))score+=4;if(regulator.includes(term))score+=3;if(body.includes(term))score+=1});return score}
function matchesJurisdiction(law, selected) {
  if (selected === "All") return true;
  if (selected === "Mainland") return ["Federal", "Dubai"].includes(law.jurisdiction);
  return law.jurisdiction === selected;
}
function search(options={scroll:true}){const q=query.value.trim();if(!q)return;current=laws.map(l=>({l,s:scoreLaw(l,q)})).filter(x=>x.s>0&&matchesJurisdiction(x.l,filter.value)).sort((a,b)=>b.s-a.s||a.l.authority.localeCompare(b.l.authority)).map(x=>x.l);render(q,options.scroll)}
function scrollToResults(){requestAnimationFrame(()=>requestAnimationFrame(()=>{const top=Math.max(0,results.getBoundingClientRect().top+window.scrollY-16);try{window.scrollTo({top,behavior:"smooth"})}catch(error){window.scrollTo(0,top)}}))}
function render(q,shouldScroll=true){intro.hidden=true;results.hidden=false;title.textContent=q;count.textContent=current.length?`${current.length} relevant instrument${current.length===1?"":"s"} across the verified starter index`:"No close match in the verified starter index";copy.hidden=!current.length;list.innerHTML=current.length?current.map((l,i)=>`<article class="card"><div class="card-num">${String(i+1).padStart(2,"0")}</div><div class="card-body"><div class="meta"><span class="pill">${l.jurisdiction}</span><span class="pill">${l.status}</span><span>${l.authority}</span></div><h3>${l.number}</h3><h4>${l.title}</h4><p>${l.summary}</p><div class="why"><b>Why it matters</b><p>${l.relevance}</p></div>${l.note?`<p class="note">Status note · ${l.note}</p>`:""}<a class="source" href="${l.source}" target="_blank" rel="noreferrer">View official source <span>↗</span></a></div></article>`).join(""):`<div class="empty"><h3>No verified match</h3><p>This static edition avoids inventing a citation when the curated index has no match. Try a shorter keyword or continue in the official UAE Legislation database.</p><a href="https://uaelegislation.gov.ae/en/legislations" target="_blank">Open UAE Legislation ↗</a></div>`;if(shouldScroll)scrollToResults()}
form.addEventListener("submit",e=>{e.preventDefault();search()});document.querySelectorAll("[data-query]").forEach(b=>b.addEventListener("click",()=>{query.value=b.dataset.query;search()}));filter.addEventListener("change",()=>search({scroll:false}));copy.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(window.mizanBriefText ? window.mizanBriefText() : current.map(l=>`${l.number} — ${l.title}\n${l.status} · ${l.jurisdiction}\n${l.summary}\nSource: ${l.source}`).join("\n\n"));copy.textContent="Copied";}catch{copy.textContent="Copy unavailable — try again";}setTimeout(()=>copy.textContent="Copy brief",1500)});
