const laws=[
 {number:"Cabinet Resolution No. 109 of 2023",title:"Regulating the Real Beneficiary Procedures",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Requires covered legal persons to identify their ultimate natural-person owners or controllers, maintain current registers and provide information to the relevant registrar.",relevance:"The core UAE beneficial-ownership instrument. It uses a 25% ownership or voting-rights test, then control by other means, followed by the senior managing official where no natural person is identified.",topics:"beneficial owner ubo ultimate ownership corporate transparency aml",source:"https://uaelegislation.gov.ae/en/legislations/2176",note:"Replaced Cabinet Decision No. 58 of 2020."},
 {number:"Cabinet Resolution No. 132 of 2023",title:"Administrative Penalties for Real Beneficiary Procedures",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Sets administrative sanctions for breaches of beneficial-ownership procedures, including escalating fines and potential licence suspension for repeated violations.",relevance:"Explains the enforcement consequences of failing to maintain or submit accurate beneficial-owner information.",topics:"beneficial owner ubo penalties ownership",source:"https://uaelegislation.gov.ae/en/legislations/2314",note:"Abrogated Cabinet Decision No. 53 of 2021."},
 {number:"Federal Decree-Law No. 10 of 2025",title:"Anti-Money Laundering and Combating Terrorism and Proliferation Financing",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"The current federal framework for anti-money laundering, counter-terrorist financing and proliferation financing.",relevance:"Provides the current parent AML framework and authorises Cabinet procedures for identifying beneficial owners.",topics:"beneficial owner ubo aml anti-money laundering ctf sanctions",source:"https://uaelegislation.gov.ae/en/legislations/3314",note:"Repealed Federal Decree-Law No. 20 of 2018."},
 {number:"Cabinet Resolution No. 134 of 2025",title:"Executive Regulations of Federal Decree-Law No. 10 of 2025",jurisdiction:"Federal",authority:"UAE Cabinet",status:"In force",summary:"Implements the current AML law, including customer due diligence, verification, record keeping and risk-based controls.",relevance:"Relevant when beneficial-owner information must be identified and verified during customer due diligence.",topics:"beneficial owner ubo aml customer due diligence cdd kyc",source:"https://uaelegislation.gov.ae/en/legislations/3857"},
 {number:"Federal Decree-Law No. 45 of 2021",title:"Personal Data Protection Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Creates the federal framework for processing personal data, data-subject rights, security, cross-border transfers and controller and processor obligations.",relevance:"The main federal instrument for organisations evaluating personal-data processing outside the financial free zones.",topics:"data protection privacy personal data cross-border transfer",source:"https://uaelegislation.gov.ae/en/legislations/1972"},
 {number:"Federal Decree-Law No. 47 of 2022",title:"Corporate Tax Law",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Establishes UAE corporate tax, including taxable persons, exemptions, calculation rules, free-zone provisions and transfer pricing.",relevance:"The primary federal law for corporate-tax questions, read with current decisions and FTA guidance.",topics:"corporate tax free zone transfer pricing",source:"https://uaelegislation.gov.ae/en/legislations/2209"},
 {number:"Federal Decree-Law No. 33 of 2021",title:"Regulation of Employment Relationships",jurisdiction:"Federal",authority:"President of the UAE",status:"In force",summary:"Regulates private-sector employment relationships, including contracts, working time, leave, termination and end-of-service benefits.",relevance:"The central federal instrument for private-sector labour and termination research, subject to its scope and later amendments.",topics:"labour employment termination end of service leave",source:"https://uaelegislation.gov.ae/en/legislations/1541"},
 {number:"DIFC Law No. 5 of 2020",title:"DIFC Data Protection Law",jurisdiction:"DIFC",authority:"Dubai International Financial Centre",status:"In force",summary:"The DIFC’s independent data-protection framework governing personal-data processing, rights, accountability and international transfers.",relevance:"Applies separately from the federal data-protection regime where the DIFC framework governs.",topics:"data protection privacy personal data difc",source:"https://www.difc.com/business/laws-and-regulations/legal-database/data-protection-law-difc-law-no-5-2020"}
];
const form=document.querySelector("#search-form"),query=document.querySelector("#query"),results=document.querySelector("#results"),intro=document.querySelector("#intro"),list=document.querySelector("#result-list"),title=document.querySelector("#results-title"),count=document.querySelector("#results-count"),filter=document.querySelector("#jurisdiction"),copy=document.querySelector("#copy");let current=[];
function search(){const q=query.value.trim().toLowerCase(),terms=q.split(/\s+/).filter(Boolean);current=laws.map(l=>({l,s:terms.reduce((n,t)=>n+(l.topics.includes(t)?4:`${l.title} ${l.summary} ${l.relevance}`.toLowerCase().includes(t)?1:0),0)})).filter(x=>x.s>0&&(filter.value==="All"||x.l.jurisdiction===filter.value)).sort((a,b)=>b.s-a.s).map(x=>x.l);render(q)}
function render(q){intro.hidden=true;results.hidden=false;title.textContent=q;count.textContent=current.length?`${current.length} relevant instrument${current.length===1?"":"s"} in the starter collection`:"No close match in the starter collection";copy.hidden=!current.length;list.innerHTML=current.length?current.map((l,i)=>`<article class="card"><div class="card-num">${String(i+1).padStart(2,"0")}</div><div class="card-body"><div class="meta"><span class="pill">${l.jurisdiction}</span><span class="pill">${l.status}</span><span>${l.authority}</span></div><h3>${l.number}</h3><h4>${l.title}</h4><p>${l.summary}</p><div class="why"><b>Why it matters</b><p>${l.relevance}</p></div>${l.note?`<p class="note">Status note · ${l.note}</p>`:""}<a class="source" href="${l.source}" target="_blank" rel="noreferrer">View official source <span>↗</span></a></div></article>`).join(""):`<div class="empty"><h3>No verified match</h3><p>Try a shorter topic or continue in the official UAE Legislation database.</p><a href="https://uaelegislation.gov.ae/en/legislations" target="_blank">Open UAE Legislation ↗</a></div>`}
form.addEventListener("submit",e=>{e.preventDefault();if(query.value.trim())search()});document.querySelectorAll("[data-query]").forEach(b=>b.addEventListener("click",()=>{query.value=b.dataset.query;search()}));filter.addEventListener("change",search);copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(current.map(l=>`${l.number} — ${l.title}\n${l.status} · ${l.jurisdiction}\n${l.summary}\nSource: ${l.source}`).join("\n\n"));copy.textContent="Copied";setTimeout(()=>copy.textContent="Copy brief",1500)});
